from datetime import date
from typing import Protocol

from mmqp.domain.assets import AssetVersion, ProviderAssetMapping


class AssetRegistryRepository(Protocol):
    def find(self, asset_id: str) -> AssetVersion | None: ...
    def as_of(self, asset_id: str, observation_date: date) -> AssetVersion | None: ...
    def create(self, asset: AssetVersion) -> AssetVersion: ...
    def history(self, asset_id: str) -> list[AssetVersion]: ...
    def close(self, asset_id: str, effective_end: date) -> AssetVersion | None: ...

    def create_provider_mapping(self, mapping: ProviderAssetMapping) -> ProviderAssetMapping: ...

    def provider_mappings(
        self,
        *,
        provider: str,
        provider_code: str,
        observation_date: date,
    ) -> list[ProviderAssetMapping]: ...
