from builtins import list as list_type
from datetime import date
from typing import Protocol

from mmqp.domain.calendars import TradingCalendarVersion, ValuationCalendarVersion


class TradingCalendarRepository(Protocol):
    def create(self, version: TradingCalendarVersion) -> TradingCalendarVersion: ...
    def list(
        self, market: str | None = None, exchange: str | None = None
    ) -> list_type[TradingCalendarVersion]: ...
    def select(self, market: str, exchange: str, as_of: date) -> list_type[TradingCalendarVersion]: ...
    def close(self) -> None: ...


class ValuationCalendarRepository(Protocol):
    def create(self, version: ValuationCalendarVersion) -> ValuationCalendarVersion: ...
    def list(self, market: str | None = None) -> list_type[ValuationCalendarVersion]: ...
    def select(self, market: str, as_of: date) -> list_type[ValuationCalendarVersion]: ...
    def close(self) -> None: ...
