from typing import Protocol

from mmqp.domain.workspace import WorkspaceRecord


class WorkspaceRepository(Protocol):
    def create(self, workspace: WorkspaceRecord) -> WorkspaceRecord: ...
    def get(self, workspace_id: str) -> WorkspaceRecord | None: ...
    def get_by_path(self, path: str) -> WorkspaceRecord | None: ...
    def list(self) -> list[WorkspaceRecord]: ...
